### PR TITLE
Update functions2.sh

### PR DESCRIPTION
**Pull request by rmctr**
Typo?

I am not so familiar with GitHub, so I did not know how to communicate the remark; I hope I did so correctly.

### CODE REVIEW

**Comment by rmctr** [comment]
Is there any way I can contact you?  I've been spending months merging various mods using complicated processes, to which your scripts were of essence, into a Magisk module to unlock the Redmi Note 10 Pro's max sample rate and bit depth, and upsample everything via the Izotope parameters listed, along with your alsa library patches for 192 kHz, and some stuff (I can't quite remember it all).  I even used AML to merge some components in the module (obviously just using its files, not requiring AML for the mod).  I would much appreciate if you were able to have a quick look and give your opinion.  

Reason I chose Izotope parameters is your suggested ones for A12+ were too heavy on the CPU, and bit perfect even more so.  Izotope is a professional software, so I figured using those parameters you listed for it would be a wise idea.

**Comment by rmctr** [comment]
@yzyhk904

**Comment by yzyhk904** [comment]
It isn't any typo. The length of prop2 must be equal to that of prop1 so that the prop1 string in a binary file can be replaced with a new string safely.

In [USB SampleRate Changer](https://github.com/yzyhk904/USB_SampleRate_Changer), there is a script "extras/change-resampling-quality.sh" to change the resampling parameters on the fly. Try "-c 179 408 99".  I feel that It's the best for up-sampling and relatively light.

**Comment by rmctr** [comment]
Thanks.  It is a bad idea to upsample to 192 kHz (supported) rather than using 48 kHz output?

**Comment by yzyhk904** [comment]
Why 192kHz? Have you used ["USB SampleRate Changer"](https://github.com/yzyhk904/USB_SampleRate_Changer)? You can up-sample up to 768kHz or 386kHz (depended on your DAC) & 32bits. "-c 179 408 99" 32bit re-sampling is much better than the over-sampling in a DAC.  So "bit-perfect" and other low sample rates are meaningless in usual under this situation.

**Comment by rmctr** [comment]
My DAC only goes to 192 kHz & 24-bit

**Comment by rmctr** [comment]
Is it a good idea to use the method I described and upsample everything to 192 kHz and 24-bit?  I was told it is bad.

**Comment by rmctr** [comment]
also, if you would ever have free time, i'd love if you checked out my module.  it is based on yours but tailored for Redmi Note 10 Pro.  it would be appreciated by many, as this phone has tends of thousands of active users on Telegram.

**Comment by yzyhk904** [comment]
usb-samplerate-unlocker doesn't depend on devices, but is universal. Because it just patches /vendor/lib64/alsautils.so and additionally set some properties. Is this to do with USB_SampleRate_Changer?

Up-sampling everything to 192kHz and 24bit depth isn't bad though I recommended "-c 179 408 99" original parameter (set in "audio-misc-settings" my another module).

**Pull request closed without merging**
